Repository peterprospl12/breathing-classification-v2, pull requests merged in 2025-04, with the labels that each got.

#24 Services and server refactor
  API/row_audio_socket_server.py
  API/server_dependencies/server_dependecies.py
  app/devtools_options.yaml
  app/lib/screens/home_screen.dart
  app/lib/services/ReadMe.md
  app/lib/services/audio_file_service.dart
  app/lib/services/audio_recording_service.dart
  app/lib/services/audio_service.dart
  app/lib/services/breath_tracking_service.dart
  app/lib/services/socket_service.dart
  app/lib/widgets/microphone_visualization.dart
  app/pubspec.yaml
Labels: enhancement

#52 Add new readme skeleton
  README.md
Labels: documentation

#63 App bug fixing
  app/android/app/src/main/AndroidManifest.xml
  app/lib/screens/home_screen.dart
  app/lib/services/breath_tracking_service.dart
Labels: fix
